### ISSUE TITLE
Zeus module not fully functioning

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Operation-Sons-of-Heaven#4]
Need to take a look at the Zeus module and settings to see what the problem is with it. Not getting all options in the initial test I ran last night.

**Comment by coachwn** [comment]
- [ ] Troops not accessible by Zeus unless placed by GM 
- [ ] No add/remove function
- [ ] Limited options for adding or adjusting functionality (ACE medical, switching sides, etc...)
- [ ] No teleport function within Zeus

**Comment by coachwn** [comment]
Still not getting fully functioning Zeus module.

**Comment by Jmaster9999** [comment]
Dumb question: Are you using ares? and is it loaded as a server mod?


Also It may be possible that the Zeus add-ons are set to "Only official addons."  Make sure the add-on options are set to "all add-ons including unoffical"

**Comment by coachwn** [comment]
Yep it is set properly and Ares is set to run properly also.

**Comment by coachwn** [comment]
For some stupid reason Battleye was blocking Ares from running on my end. I spent many hours digging through the RPT logs to find that little nugget fest and now it appears to be running correctly.

**Comment by coachwn** [comment]
Should have been closed a long time ago.
